### ISSUE TITLE
Per-Column filtering

### ISSUE THREAD

**Issue by zamblas** [savannabits/primevue-datatables#16]
In the readme it mentions `Per-Column filtering out of the box`, how can we apply it?

I'm using it like the example on primevue, but filterModel is undefined

![image](https://github.com/savannabits/primevue-datatables/assets/16827836/d29ddf60-8dc6-47b3-9629-a3d2110e9bca)

**Comment by zamblas** [comment]
I was missing that field on the filters object and it was also loading a previous configuration from localStorage

**Comment by gereyes** [comment]
Hello, how did you solve the problem?

I'm not sure what configuration I need to do but I get the same error and I don't know how to fix it.

**Comment by zamblas** [comment]
![image](https://github.com/savannabits/primevue-datatables/assets/16827836/84ffd0b4-06b0-4d45-bfe4-c18e1ff0d933)

you need to define the fields on the columnFilters

**Comment by gereyes** [comment]
Thank you very much, you saved me from making the table component from scratch.
